[package]
name = "influent"
version = "0.2.0"
authors = ["gobwas <gobwas@gmail.com>"]

description = "InfluxDB Rust driver"
documentation = "http://gobwas.github.io/influent.rs/influent/index.html"
repository = "https://github.com/gobwas/influent.rs"
readme = "README.md"
keywords = ["influx", "influxdb"]
license = "MIT"

[dependencies]
hyper = "0.6.8"
log = "0.3.1"