[package]
name = "influent"
version = "0.2.1"
authors = ["gobwas <gobwas@gmail.com>"]

description = "InfluxDB Rust driver"
documentation = "http://gobwas.github.io/influent.rs/influent/index.html"
repository = "https://github.com/gobwas/influent.rs"
readme = "README.md"
keywords = ["influx", "influxdb"]
license = "MIT"

[features]
default = ["http"]
http = ["hyper"]

[dependencies]
hyper = { version = "0.6.8", optional = true }
log = "0.3.1"
